Repository CosmWasm/cosmwasm, pull requests merged in 2021-03, with the labels that each got.

#804 Add benchmarks-based signature verification gas costs
  packages/vm/src/environment.rs
  packages/vm/src/imports.rs
Labels: Crypto APIs (AssemblyScript Reallocation)

#808 Ensure pinning a contract that is already pinned is cheap
  packages/vm/src/cache.rs
  packages/vm/src/modules/pinned_memory_cache.rs
Labels: automerge

#805 Clru-rs upstream integration
  .circleci/config.yml
  Cargo.lock
  contracts/burner/Cargo.lock
  contracts/crypto-verify/Cargo.lock
  contracts/hackatom/Cargo.lock
  contracts/ibc-reflect-send/Cargo.lock
  contracts/ibc-reflect/Cargo.lock
  contracts/queue/Cargo.lock
  contracts/reflect/Cargo.lock
  contracts/staking/Cargo.lock
  packages/vm/Cargo.toml
  packages/vm/src/modules/in_memory_cache.rs
Labels: automerge

#811 Update to rust 1.50.0
  .circleci/config.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  MIGRATING.md
  contracts/crypto-verify/src/contract.rs
  contracts/crypto-verify/src/msg.rs
  contracts/ibc-reflect-send/src/contract.rs
  contracts/ibc-reflect-send/src/ibc.rs
  contracts/queue/src/contract.rs
Labels: automerge

#815 Fix hackatom contract
  contracts/hackatom/schema/system_msg.json
  contracts/hackatom/src/contract.rs
  packages/vm/README.md
  packages/vm/src/instance.rs
  packages/vm/testdata/hackatom_0.14.wasm
Labels: automerge

#814 Make label in WasmMsg::Instantiate non-optional
  CHANGELOG.md
  contracts/ibc-reflect-send/schema/handle_msg.json
  contracts/ibc-reflect-send/schema/packet_msg.json
  contracts/ibc-reflect/schema/packet_msg.json
  contracts/ibc-reflect/src/contract.rs
  contracts/ibc-reflect/tests/integration.rs
  contracts/reflect/schema/handle_msg.json
  contracts/reflect/schema/response_for__custom_msg.json
  packages/std/schema/cosmos_msg.json
  packages/std/src/results/cosmos_msg.rs
Labels: automerge

#833 Make execute entry point optional
  CHANGELOG.md
  contracts/burner/examples/schema.rs
  contracts/burner/schema/execute_msg.json
  contracts/burner/src/contract.rs
  contracts/burner/src/msg.rs
  contracts/crypto-verify/examples/schema.rs
  contracts/crypto-verify/schema/execute_msg.json
  contracts/crypto-verify/src/contract.rs
  contracts/crypto-verify/src/msg.rs
  packages/vm/src/compatibility.rs
  packages/vm/src/instance.rs
  packages/vm/src/static_analysis.rs
Labels: automerge

#824 Return full ChannelInfo on Ibc ListChannels query
  contracts/reflect/schema/query_msg.json
  packages/std/src/ibc.rs
Labels: automerge

#840 Add synchronized access to get_instance
  packages/vm/src/cache.rs
Labels: enhancement
