Repository CosmWasm/cosmwasm, pull requests merged in 2021-01, with the labels that each got.

#707 Document omitted "sender" fields for all message types
  CHANGELOG.md
  MIGRATING.md
  contracts/burner/src/contract.rs
  contracts/burner/tests/integration.rs
  contracts/hackatom/src/contract.rs
  contracts/hackatom/tests/integration.rs
  contracts/reflect/schema/handle_msg.json
  contracts/reflect/schema/handle_response_for__custom_msg.json
  contracts/reflect/src/contract.rs
  contracts/reflect/tests/integration.rs
  contracts/staking/src/contract.rs
  packages/std/schema/cosmos_msg.json
  packages/std/src/coins.rs
  packages/std/src/results/context.rs
  packages/std/src/results/cosmos_msg.rs
  packages/std/src/results/init.rs
Labels: Breaking (interface), automerge

#708 Make query endpoint optional
  CHANGELOG.md
  contracts/README.md
  contracts/burner/examples/schema.rs
  contracts/burner/schema/query_msg.json
  contracts/burner/src/contract.rs
  contracts/burner/src/msg.rs
  packages/vm/src/compatibility.rs
  packages/vm/src/instance.rs
Labels: Breaking (consensus), automerge

#706 Add stargate msg
  packages/std/Cargo.toml
  packages/std/src/exports.rs
  packages/std/src/query.rs
  packages/std/src/results/cosmos_msg.rs
Labels: automerge

#720 Update to serde json wasm 0.3.0
  Cargo.lock
  contracts/burner/Cargo.lock
  contracts/hackatom/Cargo.lock
  contracts/hackatom/tests/integration.rs
  contracts/queue/Cargo.lock
  contracts/reflect/Cargo.lock
  contracts/staking/Cargo.lock
  packages/std/Cargo.toml
  packages/vm/README.md
  packages/vm/src/instance.rs
  packages/vm/testdata/hackatom_0.14.wasm
Labels: Performance Improvements (Productionize Code), automerge

#722 Memory cache modules size
  .gitignore
  Cargo.lock
  packages/vm/Cargo.toml
  packages/vm/README.md
  packages/vm/examples/module_size.rs
  packages/vm/examples/module_size.sh
  packages/vm/src/lib.rs
Labels: Performance Improvements (Productionize Code)

#728 IBC Enhancements
  CHANGELOG.md
  contracts/ibc-reflect/schema/packet_msg.json
  contracts/ibc-reflect/src/contract.rs
  contracts/ibc-reflect/tests/integration.rs
  contracts/reflect/schema/handle_msg.json
  contracts/reflect/schema/handle_response_for__custom_msg.json
  packages/std/src/ibc.rs
  packages/std/src/lib.rs
  packages/std/src/mock.rs
  packages/vm/README.md
  packages/vm/src/ibc_calls.rs
  packages/vm/testdata/ibc_reflect.wasm
  packages/vm/testdata/ibc_reflect_0.14.wasm
Labels: automerge

#709 Remove MessageInfo argument from migrate entry point
  contracts/burner/src/contract.rs
  contracts/burner/tests/integration.rs
  contracts/hackatom/src/contract.rs
  contracts/hackatom/tests/integration.rs
  contracts/queue/src/contract.rs
  contracts/queue/tests/integration.rs
  packages/std/src/entry_points.rs
  packages/std/src/exports.rs
  packages/vm/src/calls.rs
  packages/vm/src/environment.rs
  packages/vm/src/testing/calls.rs
  packages/vm/testdata/hackatom_0.14.wasm
Labels: Breaking (interface), automerge

#740 Add ibc reflect send contract
  .circleci/config.yml
  contracts/README.md
  contracts/ibc-reflect-send/.cargo/config
  contracts/ibc-reflect-send/Cargo.lock
  contracts/ibc-reflect-send/Cargo.toml
  contracts/ibc-reflect-send/README.md
  contracts/ibc-reflect-send/examples/schema.rs
  contracts/ibc-reflect-send/schema/account_response.json
  contracts/ibc-reflect-send/schema/admin_response.json
  contracts/ibc-reflect-send/schema/handle_msg.json
  contracts/ibc-reflect-send/schema/init_msg.json
  contracts/ibc-reflect-send/schema/list_accounts_response.json
  contracts/ibc-reflect-send/schema/packet_msg.json
  contracts/ibc-reflect-send/schema/query_msg.json
  contracts/ibc-reflect-send/src/contract.rs
  contracts/ibc-reflect-send/src/ibc.rs
  contracts/ibc-reflect-send/src/ibc_msg.rs
  contracts/ibc-reflect-send/src/lib.rs
  contracts/ibc-reflect-send/src/msg.rs
  contracts/ibc-reflect-send/src/state.rs
  contracts/ibc-reflect-send/tests/integration.rs
  contracts/ibc-reflect/src/contract.rs
Labels: automerge

#747 Weigthed lru
  Cargo.lock
  contracts/burner/Cargo.lock
  contracts/hackatom/Cargo.lock
  contracts/ibc-reflect/Cargo.lock
  contracts/queue/Cargo.lock
  contracts/reflect/Cargo.lock
  contracts/staking/Cargo.lock
  packages/vm/Cargo.toml
  packages/vm/src/cache.rs
  packages/vm/src/modules/file_system_cache.rs
  packages/vm/src/modules/in_memory_cache.rs
Labels: Performance Improvements (Productionize Code), enhancement
